### ISSUE TITLE
Move around in a buffer with h, j, k, l

### ISSUE THREAD

**Issue by Kazark** [PolyglotSymposium/void#19]
As a Vim user, the absolute minimum Normal mode commands I need are <kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, and <kbd>l</kbd>. Arrow keys also may be low-hanging fruit here.

**Comment by Kazark** [comment]
I'm going to start work on this. However, this is a big enough thing that we could probably subdivide it if you want to work on it too, @mjgpy3.
1. For starters, if we implement <kbd>CTRL</kbd>-<kbd>E</kbd> and <kbd>CTRL</kbd>-<kbd>Y</kbd> first, then we will have a basis for handling the boundary cases for `h` and `k` by the time we get there.
2. There is the whole issue of drawing the cursor, and who knows what other flaws in the UI code that may dredge up.
3. Then there is the code to sketch out the concept of motions.
4. Then there is tying everything together to get this working.

I'm happy to do the whole thing or work together on it.

**Comment by Kazark** [comment]
Started working on the first part described above on the [feature/ctrl-e-ctrl-y](https://github.com/PolyglotSymposium/void/tree/feature/ctrl-e-ctrl-y) branch.

**Comment by mjgpy3** [comment]
Dude, can I hop in on this somehow?

**Comment by Kazark** [comment]
Yeah, you could work on getting the cursor to draw. Or you could test-drive some stuff in Void.Core for having the cursor respond to the movement commands I introduced, and not worry about plugging it in yet. I.e., feel free to do the actual core implementation of h, j, k, l and we can work on propagating it through the app once I finish what I'm doing with CTRL-E and CTRL-Y. If you do anything, branch off my branch. If you want to talk about it more sometime, that's cool to.

**Comment by Kazark** [comment]
Point 1 and point 3 from above are implemented in #58. That turned out to be a fairly large chunk in itself, so I am pushing the rest of this into the next release.
