### ISSUE TITLE
Travis/Slack integration

### ISSUE THREAD

**Issue by Kazark** [PolyglotSymposium/void#44]
Since I think I'm the only one who gets "build failed" emails from Travis, even if @mjgpy3 has failed the build, it would be nice to get Travis integrated with Slack.

To do this in a secure way, we need to use the Travis CLI to safely add our Slack integration information to our `.travis.yml`. @mjgpy3 Since you are the VM/Ruby man, would you be able to do this?

**Comment by mjgpy3** [comment]
Sure, I'll look at this after work!

**Comment by mjgpy3** [comment]
Ah, those buttons!
