### ISSUE TITLE
Support switching command mode language to IronPython

### ISSUE THREAD

**Issue by Kazark** [PolyglotSymposium/void#48]
It might be useful to receive the [IronPython interpreter](https://www.nuget.org/packages/IronPython.Interpreter/) as a NuGet package in order to accomplish this.

**Comment by mjgpy3** [comment]
Ooooooo. :fireworks:

**Comment by mjgpy3** [comment]
Can you give an example of what this means exactly?

**Comment by Kazark** [comment]
Yes, sure. I was very lazy in the writeup of this issue.

My idea is that command mode is decoupled from the language. Actually, that's not just my idea, I've already implemented it that way.

In Vim, `:python "print 'Hello, world!'"` executes that Python command, but invoking the `:python` command without an argument results in an error.

In Bash, `$ python -c "print 'Hello, world!'"` executes that Python command, and invoking the `:python` command without an argument starts the REPL.

The idea is that in Void, `;python "print 'Hello, world!'"` would execute that IronPython command _in the context of Vim_ (i.e. unlike in Vim, it would have the same effect as VoidScript `;echo "Hello, world!"`), but invoking the `:python` command without an argument would switch command mode to execute commands via IronPython. Thus, subsequently, you would type `;print "Hello, world!` instead of VoidScript `;echo "Hello, world!"`. Presumably Void editor modules would be imported automatically.

This also means that you could write extensions in Python easily, and find it easier to test them, etc. In theory, we could do this with IronRuby, Lua, JavaScript, whatever...

Note that this is a distinct concept from loading Python up (without having it hooked into the editor, i.e. unable to run Void-internal commands) in a terminal buffer. That would probably look like `;terminal python`.

**Comment by mjgpy3** [comment]
Awesome, thank you. How many Iron*'s are we looking to support here eventually?

**Comment by Kazark** [comment]
I don't care how many. In a way, at this stage, I don't care at all. I don't know if I would even use it. This would be highly dependent on whether we started to get a community built up around Void, and what they wanted.

The thing I care about is this: :boom: **designing for composability** :boom:.

**Comment by Kazark** [comment]
In other words, I don't really care in the end whether we extend Void or not. (This would really be implemented in a plugin, even if it was a plugin that came with Void out of the box.) The thing I care about is the fact that there is an extension point available to plug into. So I put this issue here mostly so we would design with it in mind.

**Comment by mjgpy3** [comment]
:+1: makes sense, thanks!
