### ISSUE TITLE
Bootstrap VoidScript

### ISSUE THREAD

**Issue by Kazark** [PolyglotSymposium/void#9]
Command mode in Vim is essentially VimL REPL. Command mode in Void will also be a REPL for VoidScript (or should we call it VoidLang, to allow for the possibility of writing a compiler for it? I don't like VoidL because it's not very pronounceable). However, it could also be a Python REPL, or any other arbitrary scripting language, in the long term.

I think that the Void Core and the VoidScript implementation should be decoupled. I propose a project structure something like this: `Void.UI` depends on `Void`, which is the integration point. `Void` depends on `Void.ViewModel`, `Void.Core`, `Void.Lang.Parser`, and `Void.Lang.Interpreter`, and uses functional dependency injection to glue it all together. The `Void` project would also therefore be an injection point for extensions written in F# or other .NET languages. The integration/glue logic that is currently in `Void.ViewModel` would be moved to this project. `Void.ViewModel` depends on `Void.Core`, and `Void.Lang.Interpreter` depends on `Void.Lang.Parser`. Void.Core takes a loosely coupled dependency on the interpreter and the parser; basically, functions which are just entry points to them. Also, it exposes an API to them, which is essentially wrapped as a VoidScript module in the `Void` project, and passed into the interpreter. Thus, the core editor logic is not directory coupled to the interpreter, nor is the interpreter coupled directly to the core editor logic. In theory, you could run VoidScript outside the editor, and you could use a different scripting/command language with the editor.

VoidScript will try to provide good enough VimL compatability that scripts can be easily ported. This is because there is large amounts of valuable code written in VimL which may be useful to port to VoidScript. However, when it comes down to insane things like `"` being used for comments, no acrobatics will be performed in an attempt to provide compatibility. This will be considered to be something which must be handled during the port.

Anything that is Void (editor) specific should not be part of the core language but could be loaded up into a module. The language needs to provide a facility to interop with F# and call F# functions. Do to so, it needs at least basic support for F# types. I suggest a syntax like this: the expression `;;Command#Quit` would map to the `Command.Quit` discriminated union type in F#, and `;;Command#Write("~/.vimrc")` would map to an instance of `Command.Write` where `Write` is a member of a discriminated union that takes a string, or a string option. I am suggesting this syntax because `#` is already VimL's notation that is like `.` or `::` in most languages, and because I think that `;` will not conflict with anything currently in VimL's expressions (there are not many symbols free for that, and `;` is a nicely convenient one to type) and a single `;` is too likely to cause confusion with its use in other languages (line break) or with its general Void meaning, i.e. to mark out a piece of VoidScript (since Void uses `;` for command mode where Vim uses `:`).

Thus considered, even commands such as `;wq` could be implemented in VoidScript itself. The important thing here to my mind is to keep them from being coupled directly into the language itself.

Furthermore, the function and command API of VimL is a rag-tag collection of stuff designed by an old C guy; one whom I highly respect, but not one whose API I care to tie myself to. Therefore, functions that provide compatibility with VimL functions should really be loaded from another module, even those that aren't directly coupled to the editor. For example, I think that VoidScript should support a Boolean type, with `true` and `false` instead of `1` and `0`. The old VimL API that uses `1` and `0` for `true` and `false` should really be contained to a module rather than being VoidScript's own native builtin API.

This strategy should allow a high degree of VimL compatibility, while at the same time allowing VoidScript to grow into a somewhat more mature and modern language than VimL (not that it would ever be _that_ great). The hope is to be able to quickly port some of the many existing plugins but also to ease the transition for VimL wizards in learning to program Void. And even though VoidScript is of course a language intended for programming Void, it just does not feel right to closely couple an editor with a language, two greatly disparate concerns.

Also, if one wants to go crazy fanatical far into the future, this would allow an easier tie-in of Lua or a Lisp dialect or Python or JavaScript or even a freshly designed Void-specific scripting language.

I also think that VoidScript should position itself for the possibility of having a compiler some day, while focusing on being a scripting, configuration and command language for now. Not because that is a great and important goal, or could provide any value that is visible at this point, but because I think it is likely to encourage good language design. For example, I think that the type system from VimL should be boned up, particularly where it integrates with F#; but why not everywhere? Besides, perhaps a VoidScript -> F# transpiler would provide valuable for running on current Vim plugins as a starting point for a full, compiled Void plugin.

I think where possible, current VimL oddities should either be generalized or eliminated.

I think certain VimL constructs should be supported with a deprecation warning.

I think the initial focus should be on getting the stuff need for day-to-day command mode use working, but with an openness to extension to a fuller scripting language.

@mjgpy3 Since you are a language design affectionada, I covet your input at some point! No rush. I really shouldn't start this until I am done with the WinForms stuff. (You are welcome to start it, of course.) However, if you don't get around to thinking about it commenting on it for a while, don't worry. Still, I would love your input!

**Comment by Kazark** [comment]
Also I'm thinking that the modules mentioned above for editor integration and VimL compatibility should live neither in Void's core editor logic nor in the core of the language implementation itself. They should probably live in separate modules, like `Void.Lang.Editor` for a `Void#Editor` module and `Void.Lang.VimL` for a `Void#VimL` module, or the like.

In addition, I think it may be necessary to have an odd sort of line-based parsing system in which after the command has been parsed, it determines the parser and even the tokenizer for the rest of the line. For example, VimL commands like `:global` and `:substitute` will require something to parse `/<regex>/<regexy-stuff>/<options>`, where the slashes can also be other character instead. This seems like a specialized parse as a opposed to, say, `:w` or `:e` or `:normal`, which seem to take the raw text after them (though not entirely unparsed, I suppose, in the case of `:w` and `:e`), or `:execute`, `:echo`, and `:call`, which take expressions. It would be good if we could boil all these down into a few different types of parse, and then have a facility in the language to define commands declaring which parse they need (probably something more low-level than `:command`, though if I recall Tim Pope may have a command that mimics `:substitute` in Abolish; then again, Tim Pope is Tim Pope and he may very well have done this by his own deep magic rather than by some builtin faculty of `:command`). In my mind, this should allow for accommodating the multitude of parses that are possible in VimL while imposing some reason and order on it and decoupling the language from implementing all those commands in its core.

Also it might be neat to in some manner expose some .NET/F# APIs and to have those more as VoidScript's native APIs and implement a VimL-style API based on them _in VoidScript_.

**Comment by Kazark** [comment]
In addition, we would probably want to ditch the "user-defined command must start with a capital letter" rule. First of all, I'm not a fan of that; it creates an annoying distinction between builtin Vim things and things that might as well be builtin, i.e. it doesn't allow add-ons to feel seamless. But in addition, it conflicts with the general direction I'm laying out here in which many of the "builtin" things will actually be "user-defined".

**Comment by mjgpy3** [comment]
> I think that the Void Core and the VoidScript implementation should be decoupled

I agree and your proposed dependency graph sounds promising until I know better.

> Do to so, it needs at least basic support for F# types

If F# is anything like Haskell, this may be much easier said than done (here's a [graph](http://blogs.msdn.com/b/saeed/archive/2009/03/14/haskell-class-hierarchy-diagram.aspx) someone sketched up of Haskell's hierarchy around numbers only). This may be far fetched, but can we aim for compatibility with CLR rather than F#? I'm not really sure if this comment makes any sense, just throwing it out there.

> Thus considered, even commands such as ;wq could be implemented in VoidScript itself. The important thing here to my mind is to keep them from being coupled directly into the language itself.

This again seems to indicate that we should write for CLR and not F#, C#, IronPython or what have you. If this makes no sense, please say so.

> the function and command API of VimL is a rag-tag collection of stuff designed by an old C guy; one whom I highly respect, but not one whose API I care to tie myself to

What about just a VimL -> VoidScript transpiler? That sounds simpler (albeit probably not a perfect solution) than a similar-but-not-fully-compatible model.

> ease the transition for VimL wizards in learning to program Void

I'd shoot for a lower common denominator than this. My hypothesis is that VimL wizards are likely to be good programmers, however, not all good programmers are VimL wizards. I'd rather have a language that good programmers can adopt easily than VimL wizards. For example, I'd wager emacs LISP is more widely used that VimL (not a fact, just a wager).

> I also think that VoidScript should position itself for the possibility of having a compiler some day, while focusing on being a scripting, configuration and command language for now

I guess this sounds a little anti-CLR, huh?

>  For example, I think that the type system from VimL should be boned up, particularly where it integrates with F#; but why not everywhere?

This makes a lot of sense to me

> I think where possible, current VimL oddities should either be generalized or eliminated.

Agreed

> I think the initial focus should be on getting the stuff need for day-to-day command mode use working, but with an openness to extension to a fuller scripting language.

Sounds good to me, sort of the agile-esque, let it grow organically style of development.

It's a little late, so I hope this is all coherent. Let me know your thoughts.

**Comment by Kazark** [comment]
@mjgpy3 ! So delighted to see you commenting on this issue.

Your thought on types is a good point. Honestly I was thinking that at least preliminarily it wouldn't have anything like full support for F#'s type system. Rather, it would have just enough support for it to actually invoke F# functions smoothly. At least at first, you probably wouldn't be able to define discriminated unions in VoidScript or anything like that; you would just be able to reference ones defined in F# libraries. However, I don't think F#'s numeric system is anything like Haskell's. It seems a lot more mundane.

I do not want to write a transpiler for VimL -> VoidScript because part of the reason I am attempting to avoid implementing full VimL is I don't want to put myself through all the many extremely vexing parses. Also if the Void command mode is to have anything like a strong compatibility with Vim's command mode then there will need to be at a minimum a strong resemblance between the languages. Honestly, my goal **isn't** to make VoidScript the ultimate language for programming Void. In my mind, that language is probably F#. I just want to make VoidScript easier to implement than VimL and cleaner than VimL. I'm okay with VoidScript still being a bit of a ragtag language. What do you think? Do you have a further thought on the transpiler?

I like your thought about making VoidScript a more programmable language in order to more easily attract people who are good programmers but have perhaps been averse (and understandably so) to VimL.

> > I also think that VoidScript should position itself for the possibility of having a compiler some day, while focusing on being a scripting, configuration and command language for now
> 
> I guess this sounds a little anti-CLR, huh?
> No... if it had a compiler it would probably compile to the .NET platform. Or am I misunderstanding your comment?

I am not yet sure whether it is necessary to make the distinction between targeting F# or the .NET framework. Those two things may not be opposites.

Thanks for your thoughts! Post more as they come to you.

**Comment by Kazark** [comment]
Upon further reflection, I don't think there is a need for a special syntax to denote discriminated unions. The VimL  identifier syntax shouldn't exclude the possibility of extending the type system.

We do need to realize, though (and embrace) that if we take the decoupled model that I have offered here, that will have downstream effects that we can't fully foresee right now, because VimL is a language that is tightly coupled into the Vim editor, and I am proposing we decouple them.

**Comment by Kazark** [comment]
I'm starting a spike branch for this, but that does not mean this conversation is over, it just means that it is beginning in earnest. My goal for now is to get a few basics commands working that can be plugin in to activate command mode.

**Comment by Kazark** [comment]
The branch where I have started some work on this is [feature/voidscript-spike](https://github.com/PolyglotSymposium/void/tree/feature/voidscript-spike).

**Comment by Kazark** [comment]
Someday I think VoidScript should live in its own project. If we carry through with decoupling it from the editor, that would really enforce the boundary line. Void could receive VoidScript as a NuGet package.

Right now I think this would be a hindrance to development since they are both so early-stage. It would be a premature abstraction. But I think that at some point we may be ready to do that.
